import React from 'react';
import Head from 'next/head';
import { GetServerSideProps, InferGetServerSidePropsType } from 'next';
// import { Inter } from 'next/font/google';
import { Layout } from '@components';
import { type GetBreakpoint, getBreakpoint } from '@utils/getBreakpoint';
import { useBreakpoint } from '@utils/useBreakpoint';
import { BreakpointContext } from '@utils/breakpointContext';

// const inter = Inter({ subsets: ['latin'] });
type Props = {
  serverBreakpoint: GetBreakpoint;
};

export const getServerSideProps: GetServerSideProps<Props> = async ({
  req,
}) => {
  const serverBreakpoint = getBreakpoint(req);

  return {
    props: {
      serverBreakpoint,
    },
  };
};

const Home: React.FC<
  InferGetServerSidePropsType<typeof getServerSideProps>
> = ({ serverBreakpoint }) => {
  const breakpoint = useBreakpoint(serverBreakpoint);

  return (
    <>
      {/*TODO*/}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BreakpointContext.Provider value={breakpoint}>
        <Layout>
          <div>{breakpoint.isMobile ? 1 : 2}</div>
          <div>{serverBreakpoint.isMobile ? 1 : 2}</div>
        </Layout>
      </BreakpointContext.Provider>
    </>
  );
};

export default Home;
